// <auto-generated />
using System;
using Airport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airport.Data.Migrations
{
    [DbContext(typeof(AirportDbContext))]
    partial class AirportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Airport.Core.Models.BoardingPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardingGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BoardingPasses");
                });

            modelBuilder.Entity("Airport.Core.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartureTime = new DateTime(2024, 5, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Улаанбаатар",
                            FlightNumber = "MN123",
                            Gate = "A1",
                            Status = 0,
                            TotalSeats = 180
                        });
                });

            modelBuilder.Entity("Airport.Core.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Бат",
                            LastName = "Болд",
                            Nationality = "Монгол",
                            PassportNumber = "AA12345"
                        });
                });

            modelBuilder.Entity("Airport.Core.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "1A"
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "1B"
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "1C"
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "1D"
                        },
                        new
                        {
                            Id = 5,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "1E"
                        },
                        new
                        {
                            Id = 6,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "1F"
                        },
                        new
                        {
                            Id = 7,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "2A"
                        },
                        new
                        {
                            Id = 8,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "2B"
                        },
                        new
                        {
                            Id = 9,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "2C"
                        },
                        new
                        {
                            Id = 10,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "2D"
                        },
                        new
                        {
                            Id = 11,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "2E"
                        },
                        new
                        {
                            Id = 12,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "2F"
                        },
                        new
                        {
                            Id = 13,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "3A"
                        },
                        new
                        {
                            Id = 14,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "3B"
                        },
                        new
                        {
                            Id = 15,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "3C"
                        },
                        new
                        {
                            Id = 16,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "3D"
                        },
                        new
                        {
                            Id = 17,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "3E"
                        },
                        new
                        {
                            Id = 18,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "3F"
                        },
                        new
                        {
                            Id = 19,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "4A"
                        },
                        new
                        {
                            Id = 20,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "4B"
                        },
                        new
                        {
                            Id = 21,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "4C"
                        },
                        new
                        {
                            Id = 22,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "4D"
                        },
                        new
                        {
                            Id = 23,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "4E"
                        },
                        new
                        {
                            Id = 24,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "4F"
                        },
                        new
                        {
                            Id = 25,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "5A"
                        },
                        new
                        {
                            Id = 26,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "5B"
                        },
                        new
                        {
                            Id = 27,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "5C"
                        },
                        new
                        {
                            Id = 28,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "5D"
                        },
                        new
                        {
                            Id = 29,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "5E"
                        },
                        new
                        {
                            Id = 30,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "5F"
                        },
                        new
                        {
                            Id = 31,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "6A"
                        },
                        new
                        {
                            Id = 32,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "6B"
                        },
                        new
                        {
                            Id = 33,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "6C"
                        },
                        new
                        {
                            Id = 34,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "6D"
                        },
                        new
                        {
                            Id = 35,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "6E"
                        },
                        new
                        {
                            Id = 36,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "6F"
                        },
                        new
                        {
                            Id = 37,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "7A"
                        },
                        new
                        {
                            Id = 38,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "7B"
                        },
                        new
                        {
                            Id = 39,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "7C"
                        },
                        new
                        {
                            Id = 40,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "7D"
                        },
                        new
                        {
                            Id = 41,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "7E"
                        },
                        new
                        {
                            Id = 42,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "7F"
                        },
                        new
                        {
                            Id = 43,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "8A"
                        },
                        new
                        {
                            Id = 44,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "8B"
                        },
                        new
                        {
                            Id = 45,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "8C"
                        },
                        new
                        {
                            Id = 46,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "8D"
                        },
                        new
                        {
                            Id = 47,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "8E"
                        },
                        new
                        {
                            Id = 48,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "8F"
                        },
                        new
                        {
                            Id = 49,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "9A"
                        },
                        new
                        {
                            Id = 50,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "9B"
                        },
                        new
                        {
                            Id = 51,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "9C"
                        },
                        new
                        {
                            Id = 52,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "9D"
                        },
                        new
                        {
                            Id = 53,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "9E"
                        },
                        new
                        {
                            Id = 54,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "9F"
                        },
                        new
                        {
                            Id = 55,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "10A"
                        },
                        new
                        {
                            Id = 56,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "10B"
                        },
                        new
                        {
                            Id = 57,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "10C"
                        },
                        new
                        {
                            Id = 58,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "10D"
                        },
                        new
                        {
                            Id = 59,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "10E"
                        },
                        new
                        {
                            Id = 60,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "10F"
                        },
                        new
                        {
                            Id = 61,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "11A"
                        },
                        new
                        {
                            Id = 62,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "11B"
                        },
                        new
                        {
                            Id = 63,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "11C"
                        },
                        new
                        {
                            Id = 64,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "11D"
                        },
                        new
                        {
                            Id = 65,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "11E"
                        },
                        new
                        {
                            Id = 66,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "11F"
                        },
                        new
                        {
                            Id = 67,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "12A"
                        },
                        new
                        {
                            Id = 68,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "12B"
                        },
                        new
                        {
                            Id = 69,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "12C"
                        },
                        new
                        {
                            Id = 70,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "12D"
                        },
                        new
                        {
                            Id = 71,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "12E"
                        },
                        new
                        {
                            Id = 72,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "12F"
                        },
                        new
                        {
                            Id = 73,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "13A"
                        },
                        new
                        {
                            Id = 74,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "13B"
                        },
                        new
                        {
                            Id = 75,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "13C"
                        },
                        new
                        {
                            Id = 76,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "13D"
                        },
                        new
                        {
                            Id = 77,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "13E"
                        },
                        new
                        {
                            Id = 78,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "13F"
                        },
                        new
                        {
                            Id = 79,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "14A"
                        },
                        new
                        {
                            Id = 80,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "14B"
                        },
                        new
                        {
                            Id = 81,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "14C"
                        },
                        new
                        {
                            Id = 82,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "14D"
                        },
                        new
                        {
                            Id = 83,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "14E"
                        },
                        new
                        {
                            Id = 84,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "14F"
                        },
                        new
                        {
                            Id = 85,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "15A"
                        },
                        new
                        {
                            Id = 86,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "15B"
                        },
                        new
                        {
                            Id = 87,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "15C"
                        },
                        new
                        {
                            Id = 88,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "15D"
                        },
                        new
                        {
                            Id = 89,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "15E"
                        },
                        new
                        {
                            Id = 90,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "15F"
                        },
                        new
                        {
                            Id = 91,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "16A"
                        },
                        new
                        {
                            Id = 92,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "16B"
                        },
                        new
                        {
                            Id = 93,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "16C"
                        },
                        new
                        {
                            Id = 94,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "16D"
                        },
                        new
                        {
                            Id = 95,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "16E"
                        },
                        new
                        {
                            Id = 96,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "16F"
                        },
                        new
                        {
                            Id = 97,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "17A"
                        },
                        new
                        {
                            Id = 98,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "17B"
                        },
                        new
                        {
                            Id = 99,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "17C"
                        },
                        new
                        {
                            Id = 100,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "17D"
                        },
                        new
                        {
                            Id = 101,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "17E"
                        },
                        new
                        {
                            Id = 102,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "17F"
                        },
                        new
                        {
                            Id = 103,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "18A"
                        },
                        new
                        {
                            Id = 104,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "18B"
                        },
                        new
                        {
                            Id = 105,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "18C"
                        },
                        new
                        {
                            Id = 106,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "18D"
                        },
                        new
                        {
                            Id = 107,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "18E"
                        },
                        new
                        {
                            Id = 108,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "18F"
                        },
                        new
                        {
                            Id = 109,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "19A"
                        },
                        new
                        {
                            Id = 110,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "19B"
                        },
                        new
                        {
                            Id = 111,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "19C"
                        },
                        new
                        {
                            Id = 112,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "19D"
                        },
                        new
                        {
                            Id = 113,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "19E"
                        },
                        new
                        {
                            Id = 114,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "19F"
                        },
                        new
                        {
                            Id = 115,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "20A"
                        },
                        new
                        {
                            Id = 116,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "20B"
                        },
                        new
                        {
                            Id = 117,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "20C"
                        },
                        new
                        {
                            Id = 118,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "20D"
                        },
                        new
                        {
                            Id = 119,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "20E"
                        },
                        new
                        {
                            Id = 120,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "20F"
                        },
                        new
                        {
                            Id = 121,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "21A"
                        },
                        new
                        {
                            Id = 122,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "21B"
                        },
                        new
                        {
                            Id = 123,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "21C"
                        },
                        new
                        {
                            Id = 124,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "21D"
                        },
                        new
                        {
                            Id = 125,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "21E"
                        },
                        new
                        {
                            Id = 126,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "21F"
                        },
                        new
                        {
                            Id = 127,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "22A"
                        },
                        new
                        {
                            Id = 128,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "22B"
                        },
                        new
                        {
                            Id = 129,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "22C"
                        },
                        new
                        {
                            Id = 130,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "22D"
                        },
                        new
                        {
                            Id = 131,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "22E"
                        },
                        new
                        {
                            Id = 132,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "22F"
                        },
                        new
                        {
                            Id = 133,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "23A"
                        },
                        new
                        {
                            Id = 134,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "23B"
                        },
                        new
                        {
                            Id = 135,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "23C"
                        },
                        new
                        {
                            Id = 136,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "23D"
                        },
                        new
                        {
                            Id = 137,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "23E"
                        },
                        new
                        {
                            Id = 138,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "23F"
                        },
                        new
                        {
                            Id = 139,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "24A"
                        },
                        new
                        {
                            Id = 140,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "24B"
                        },
                        new
                        {
                            Id = 141,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "24C"
                        },
                        new
                        {
                            Id = 142,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "24D"
                        },
                        new
                        {
                            Id = 143,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "24E"
                        },
                        new
                        {
                            Id = 144,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "24F"
                        },
                        new
                        {
                            Id = 145,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "25A"
                        },
                        new
                        {
                            Id = 146,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "25B"
                        },
                        new
                        {
                            Id = 147,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "25C"
                        },
                        new
                        {
                            Id = 148,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "25D"
                        },
                        new
                        {
                            Id = 149,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "25E"
                        },
                        new
                        {
                            Id = 150,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "25F"
                        },
                        new
                        {
                            Id = 151,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "26A"
                        },
                        new
                        {
                            Id = 152,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "26B"
                        },
                        new
                        {
                            Id = 153,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "26C"
                        },
                        new
                        {
                            Id = 154,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "26D"
                        },
                        new
                        {
                            Id = 155,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "26E"
                        },
                        new
                        {
                            Id = 156,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "26F"
                        },
                        new
                        {
                            Id = 157,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "27A"
                        },
                        new
                        {
                            Id = 158,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "27B"
                        },
                        new
                        {
                            Id = 159,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "27C"
                        },
                        new
                        {
                            Id = 160,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "27D"
                        },
                        new
                        {
                            Id = 161,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "27E"
                        },
                        new
                        {
                            Id = 162,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "27F"
                        },
                        new
                        {
                            Id = 163,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "28A"
                        },
                        new
                        {
                            Id = 164,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "28B"
                        },
                        new
                        {
                            Id = 165,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "28C"
                        },
                        new
                        {
                            Id = 166,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "28D"
                        },
                        new
                        {
                            Id = 167,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "28E"
                        },
                        new
                        {
                            Id = 168,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "28F"
                        },
                        new
                        {
                            Id = 169,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "29A"
                        },
                        new
                        {
                            Id = 170,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "29B"
                        },
                        new
                        {
                            Id = 171,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "29C"
                        },
                        new
                        {
                            Id = 172,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "29D"
                        },
                        new
                        {
                            Id = 173,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "29E"
                        },
                        new
                        {
                            Id = 174,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "29F"
                        },
                        new
                        {
                            Id = 175,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "30A"
                        },
                        new
                        {
                            Id = 176,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "30B"
                        },
                        new
                        {
                            Id = 177,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "30C"
                        },
                        new
                        {
                            Id = 178,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "30D"
                        },
                        new
                        {
                            Id = 179,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "30E"
                        },
                        new
                        {
                            Id = 180,
                            FlightId = 1,
                            IsOccupied = false,
                            SeatNumber = "30F"
                        });
                });

            modelBuilder.Entity("Airport.Core.Models.Passenger", b =>
                {
                    b.HasOne("Airport.Core.Models.Seat", "AssignedSeat")
                        .WithOne("Passenger")
                        .HasForeignKey("Airport.Core.Models.Passenger", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedSeat");
                });

            modelBuilder.Entity("Airport.Core.Models.Seat", b =>
                {
                    b.HasOne("Airport.Core.Models.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Airport.Core.Models.Flight", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Airport.Core.Models.Seat", b =>
                {
                    b.Navigation("Passenger")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
